### ISSUE TITLE
Multiple Hosts are not Seperated

### ISSUE THREAD

**Issue by theogbubbie** [fantom732315/Grafana#2]
First of all, thanks for this JSON file. I had used this alongside a windows exporter with enabled MSSQL Metric. However, I had encountered an issue when I used this for multiple targets as it can't identify the different hosts I set. Attached is the screenshot of my issue.

![image](https://user-images.githubusercontent.com/90822060/133712346-b7e89d8f-eaab-4359-a6ce-e4a5ffcdc8f3.png)

**Comment by fantom732315** [comment]
Create separate jobs for each target, metrics are separated by job name

**Comment by theogbubbie** [comment]
Thanks for the quick response, I will try this approach.

**Comment by theogbubbie** [comment]
Hi, I did what you suggested and successfully had separated my targets per job defined on Prometheus however there are much missing data on the dashboard whenever I define the DB instance. Included is the screenshot of my current dashboard using your json file. Also, attached is the text file of the results of my metrics. 


Included below is a screenshot of my current dashboard.
![image](https://user-images.githubusercontent.com/90822060/133760938-ab408d92-ea4b-4b30-9280-ae97d0bf4b1d.png)

.

**Comment by fantom732315** [comment]
Its very strange. Check dashboard variables.

![image](https://user-images.githubusercontent.com/90676446/133763652-1b3c06a7-1ddf-47a9-a514-d08a3fbe9cfb.png)

![image](https://user-images.githubusercontent.com/90676446/133763841-5b62500d-aaf2-42ae-9a08-00e858e5faf7.png)


Do you only display the MSSQLSERVER variable in prewiev  or are there many of them (SLMCTEST, SLMCTESTES .....)?

I think the problem is in the replicas, but to be sure, you need to check

**Comment by theogbubbie** [comment]
Hi MSSQLSERVER is the only one available in the preview of values.
![image](https://user-images.githubusercontent.com/90822060/133766861-fb460eac-c449-47bd-ab71-930bdacd6e6d.png)

**Comment by theogbubbie** [comment]
May I ask how di you defined the job in the prometheus yml file?

**Comment by fantom732315** [comment]
![image](https://user-images.githubusercontent.com/90676446/133767080-db4ff067-7a3e-4540-9427-d798d4dc8db0.png)

try insert this values in Query:
label_values(windows_mssql_dbreplica_transaction_delay_seconds, replica)

Since I have no replicas, I have nothing to test on and my preview field is empty. If you display the variables, the dashboard will theoretically work
Promethues config(I have singe server with several DB)
      - job_name: 'Win'
        scrape_interval: 5s
        static_configs:
        - targets: ['10.111.111.111:9182']
